In [4]:
import pandas as pd
import os
import seaborn as sns

os.chdir(r'C:\Users\user\Desktop\전처리 데이터')

In [17]:
os.listdir()

['개발제한구역_활용현황_전처리완료.csv',
 '시군구_법정코드.xlsx',
 '연령별인구현황_전처리.xlsx',
 '읍면동_법정코드.xlsx',
 '읍면동_인구수.xlsx',
 '전국농어촌체험휴양마을표준데이터_전처리.csv',
 '전국농어촌체험휴양마을표준데이터_최종.csv',
 '전통시장통계_시군구_최종.csv',
 '폐교데이터_전처리_교육+소득증대.xlsx',
 '행정_읍면_코드.xlsx']

In [15]:
code_or = pd.read_excel('읍면동_법정코드.xlsx')
code_or.head()

    법정동코드_읍면동       법정동명_읍면동
0  1111010100  서울특별시 종로구 청운동
1  1111010200  서울특별시 종로구 신교동
2  1111010300  서울특별시 종로구 궁정동
3  1111010400  서울특별시 종로구 효자동
4  1111010500  서울특별시 종로구 창성동

In [39]:
code_new = pd.read_excel('읍면동_인구수.xlsx')
code_new = code_new.loc[:,'지역명':'code_len']
code_new.head()

               지역명       행정동코드  code_len
0  서울특별시 종로구 청운효자동  1111051500         8
1    서울특별시 종로구 사직동  1111053000         7
2    서울특별시 종로구 삼청동  1111054000         7
3    서울특별시 종로구 부암동  1111055000         7
4    서울특별시 종로구 평창동  1111056000         7

In [41]:
code_or = pd.read_excel('행정_읍면_코드.xlsx')
code_or.head()

        행정동코드    시도명 시군구명   읍면동명       법정동코드    동리명      생성일자  말소일자
0  1100000000  서울특별시  NaN    NaN  1100000000  서울특별시  19880423   NaN
1  1111000000  서울특별시  종로구    NaN  1111000000    종로구  19880423   NaN
2  1111051500  서울특별시  종로구  청운효자동  1111010100    청운동  20081101   NaN
3  1111051500  서울특별시  종로구  청운효자동  1111010200    신교동  20081101   NaN
4  1111051500  서울특별시  종로구  청운효자동  1111010300    궁정동  20081101   NaN

In [43]:
test = pd.merge(code_new, code_or, on='행정동코드', how='left')
test

,지역명,행정동코드,code_len,시도명,시군구명,읍면동명,법정동코드,동리명,생성일자,말소일자
0,서울특별시 종로구 청운효자동,1111051500,8,서울특별시,종로구,청운효자동,1111010100,청운동,20081101,NaN
1,서울특별시 종로구 청운효자동,1111051500,8,서울특별시,종로구,청운효자동,1111010200,신교동,20081101,NaN
2,서울특별시 종로구 청운효자동,1111051500,8,서울특별시,종로구,청운효자동,1111010300,궁정동,20081101,NaN
3,서울특별시 종로구 청운효자동,1111051500,8,서울특별시,종로구,청운효자동,1111010400,효자동,20081101,NaN
4,서울특별시 종로구 청운효자동,1111051500,8,서울특별시,종로구,청운효자동,1111010500,창성동,20081101,NaN
...,...,...,...,...,...,...,...,...,...,...
21408,제주특별자치도 서귀포시 중문동,5013061000,7,제주특별자치도,서귀포시,중문동,5013011400,대포동,20060701,NaN
21409,제주특별자치도 서귀포시 중문동,5013061000,7,제주특별자치도,서귀포시,중문동,5013011800,하원동,20060701,NaN
21410,제주특별자치도 서귀포시 예래동,5013062000,7,제주특별자치도,서귀포시,예래동,5013011900,색달동,20060701,NaN
21411,제주특별자치도 서귀포시 예래동,5013062000,7,제주특별자치도,서귀포시,예래동,5013012000,상예동,20060701,NaN
21412,제주특별자치도 서귀포시 예래동,5013062000,7,제주특별자치도,서귀포시,예래동,5013012100,하예동,20060701,NaN

In [44]:
test.loc[test['행정동코드'].isna()]

Empty DataFrame
Columns: [지역명, 행정동코드, code_len, 시도명, 시군구명, 읍면동명, 법정동코드, 동리명, 생성일자, 말소일자]
Index: []